### PR TITLE
Mark 1 of the simulation and control.

### PR DESCRIPTION
**Pull request by mschottdorf**
Mild updates to SensorValues and ControlSettingName. Please check if ok.

All other things are in the simulation-class. Usage is demonstrated in a jupyter-notebook in /sandbox/

### CODE REVIEW

**Comment by mschottdorf** [comment]
A comment: the merging conflict is in the usage of a few libraries. I'm not sure how do do this best. This concerns architecture. Please advise.

**Comment by gdoubleyew** [comment]
What is the merge conflict that you reference? Can you paste the conflict message here, or where do we see the message?

**Comment by gdoubleyew** [comment]
For the merge conflict, maybe we should make a /vent/common directory and put message.py in that directory.

**Comment by mschottdorf** [comment]
The merging conflict is in control_module:

<<<<<<< master
import numpy as np
import time
from .message import SensorValues, ControlSettings, Alarm, ControlSettingName
=======
from typing import List
from vent.coordinator.message import SensorValues, ControlSettings, Alarm

>>>>>>> master

class ControlModuleBase:

**Comment by gdoubleyew** [comment]
>
> I am not sure how to standardize importing libraries?

I don't think the syntax of importing needs to be standardized, if that's what you mean, both here are fine. You just need to resolve this by adding "from typing import List" to the top one and deciding where message.py will live so that it can be used by all modules. I'd suggest to put message.py in a new directory /vent/common. And then the bottom part of the merge conflict can be deleted.

**Comment by sunnyszy** [comment]
I agree with Grant. For more about the import syntax, you can check: https://stackoverflow.com/questions/22511792/python-from-dotpackage-import-syntax

**Comment by mschottdorf** [comment]
Alright, then consensus is reached. I'll make a new folder `/vent/common` and add message.py there

**Comment by mschottdorf** [comment]
One of you guys should merge the pull request.

**Pull request merged**
